[build]
builder = "nixpacks"
buildCommand = "NPM_CONFIG_PRODUCTION=false npm ci && npm run db:generate && npm run build"

[deploy]
startCommand = "npx prisma db push && npm start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
